### ISSUE TITLE
[Release] 0.2.2

### ISSUE THREAD

**Issue by darylteo** [MoOx/pjax#55]
Hey @MoOx  never done this before (npm/bower wise). 

Can you tell me how to go about it? Do I just up the version numbers in package.json/bower.json and push a release tag or do I need to do other things?

I think now that the main library is "functional" we should push it out as is and then deal with issues as they come up.

**Comment by MoOx** [comment]
Sure. I still have some questions for you:
- Do you use bower? Cause since bower is kind of dead this days, I was thinking about removing it from there.
- Is commonjs style lib enough for you? I was thinking about dropping the standalone build step (which is not very useful this days).
- let me automate the process for publising. I like to have a command that run tests, create tag, publish on npm and update releases notes based on the CHANGELOG (so watcher receive a notification with the releases notes).

**Comment by darylteo** [comment]
From the perspective of legacy maintenance

 - would still support bower if it is not too much hassle. Lots of legacy projects (i.e. anything built before 2016 ;)) is likely to still need bower for front-end dependency management
 - standalone might also still be needed (like through CDNs). I might suggest putting the artifact in a more ecosystem friendly location (/dist)
 - sure please do. I am pulling from my fork for work purposes currently anyway.

**Comment by MoOx** [comment]
Will handle that when I came back from a conference next week.

**Comment by MoOx** [comment]
- Btw, do YOU use bower?
- standalone are legacy to me (and btw, https://npmcdn.com/)

**Comment by darylteo** [comment]
Nope. Webpack npm for me (this year at least, who knows what more the js
community will come up with again by next year *sigh*)

But I am using it in at least one client legacy project right now at least.

**Comment by MoOx** [comment]
Sorry for the delay!
