### ISSUE TITLE
Replace testling (this project is dead)

### ISSUE THREAD

**Issue by MoOx** [MoOx/pjax#63]
I have 2 HDD and cannot start testling due to a really stupid bug (I opened an issue several months/years ago)

https://github.com/substack/testling/issues/111

**Comment by MoOx** [comment]
FYI https://github.com/substack/browser-launcher/pull/26

**Comment by BehindTheMath** [comment]
I've been doing research on options for testing.

It seems that since pjax doesn't do any rendering, most of the goals of testing could be achieved by just using [jsdom](https://github.com/tmpvar/jsdom). This won't indicate any browser-specific quirks, but I think as of now, those should be ironed out, and testing is really to prevent regressions.

I've gotten all the tests to pass using jsdom, with a few small fixes to account for the differences between it and a real browser.

@MoOx what's your opinion?

**Comment by BehindTheMath** [comment]
One thing that will have to changed regardless, is the REST API used for testing XHR requests. The Github API refuses requests with custom headers, due to CORS.

I've tested using [httpbin](https://httpbin.org) instead, and that seems to be working as expected.

**Comment by MoOx** [comment]
jsdom is ok for me!

**Comment by BehindTheMath** [comment]
On the subject of testing, It looks like the Travis config needs to be updated. It's running Node 0.10 and NPM 2, which are way out of date. I don't know where that's coming from, since those aren't specified in [.travis.yml](https://github.com/MoOx/pjax/blob/6491e3243787556664dc254dcc55b6af226b6786/.travis.yml)

**Comment by MoOx** [comment]
it's default travis version :/
